### ISSUE TITLE
Navigated to dev profile through a link, but the profile page DNE

### ISSUE THREAD

**Issue by Megha-Pathak** [makerdock/ttjc-mentor-review#5]
Hey @Utkarshbhimte and @viral-sangani 

So I navigated to the link - https://ttjc-reviews.netlify.app/submission/dev/Megha-Pathak

By going through submissions -> opening the submission -> clicking on the name 

Ideally, this should have taken me to my profile (github or TTJC Reviews profile) but it showed me a blank screen instead. 
See the screenshot below:

![image](https://user-images.githubusercontent.com/40709743/87624788-317af000-c746-11ea-9246-5266ed834a19.png)

Would be great if you can fix this :)

**Comment by viral-sangani** [comment]
@Utkarshbhimte I am on it.

**Comment by viral-sangani** [comment]
@Utkarshbhimte @Megha-Pathak Bug is resolved.
